In [3]:
# pip install redis

In [43]:
import redis
import json

In [13]:
redis_client = redis.Redis(host="localhost", port=6379, decode_responses=True)

In [14]:
redis_client.ping()

True

In [17]:
STREAM_KEY = 'cdc.public.mapping_id'
last_id = '0-0'

In [18]:
messages = redis_client.xread({STREAM_KEY: last_id}, count=10, block=5000)

In [19]:
messages

[['cdc.public.mapping_id',
  [('1781925133716-0',
    {'default': '{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"before"},{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"int64","optional":true,"field":"txId"},{"type":"int64","optional":true,"field":"lsn"},{"type":"int64","optional":true,"field":"xmin"}],"optional":false,"name":"io.debezium.connector.postgresql.Source","field":"source"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"}],"optional":false,"name":"cdc.public.mapping_id.Envelope","version":1},"payload":{"before":null,"after":{"index":0,"id":0,"uuid":"5039f86c-379a-462a-a8c5-a7195f9ed43e"},"source":{"version":"2.4.2.Final","connector":"postgresql","name":"cdc","ts_ms":1781925133176,"snapshot":"false","db":"sourcedb","sequence":"[null,\\"29460856\\"]","schema":"public","table":"mapping_id","txId":767,"lsn":29460856,"xmin":null},"op":"c","ts_ms":1781925133366,"transaction":null}}'}),
   ('1781925133717-0',
    {'default': '{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"before"},{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"int64","optional":true,"field":"txId"},{"type":"int64","optional":true,"field":"lsn"},{"type":"int64","optional":true,"field":"xmin"}],"optional":false,"name":"io.debezium.connector.postgresql.Source","field":"source"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"}],"optional":false,"name":"cdc.public.mapping_id.Envelope","version":1},"payload":{"before":null,"after":{"index":1,"id":1,"uuid":"e58a4d31-3dde-4435-8eb9-375642eb238f"},"source":{"version":"2.4.2.Final","connector":"postgresql","name":"cdc","ts_ms":1781925133176,"snapshot":"false","db":"sourcedb","sequence":"[null,\\"29461128\\"]","schema":"public","table":"mapping_id","txId":767,"lsn":29461128,"xmin":null},"op":"c","ts_ms":1781925133369,"transaction":null}}'}),
   ('1781925133717-1',
    {'default': '{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"before"},{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"int64","optional":true,"field":"txId"},{"type":"int64","optional":true,"field":"lsn"},{"type":"int64","optional":true,"field":"xmin"}],"optional":false,"name":"io.debezium.connector.postgresql.Source","field":"source"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"}],"optional":false,"name":"cdc.public.mapping_id.Envelope","version":1},"payload":{"before":null,"after":{"index":2,"id":2,"uuid":"2fb18656-b37e-44ea-be63-daedb0248def"},"source":{"version":"2.4.2.Final","connector":"postgresql","name":"cdc","ts_ms":1781925133176,"snapshot":"false","db":"sourcedb","sequence":"[null,\\"29461304\\"]","schema":"public","table":"mapping_id","txId":767,"lsn":29461304,"xmin":null},"op":"c","ts_ms":1781925133369,"transaction":null}}'}),
   ('1781925133717-2',
    {'default': '{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"before"},{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"int64","optional":true,"field":"txId"},{"type":"int64","optional":true,"field":"lsn"},{"type":"int64","optional":true,"field":"xmin"}],"optional":false,"name":"io.debezium.connector.postgresql.Source","field":"source"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"}],"optional":false,"name":"cdc.public.mapping_id.Envelope","version":1},"payload":{"before":null,"after":{"index":3,"id":3,"uuid":"d5a9d0da-ce82-447a-b764-b3ad028fc300"},"source":{"version":"2.4.2.Final","connector":"postgresql","name":"cdc","ts_ms":1781925133176,"snapshot":"false","db":"sourcedb","sequence":"[null,\\"29461480\\"]","schema":"public","table":"mapping_id","txId":767,"lsn":29461480,"xmin":null},"op":"c","ts_ms":1781925133370,"transaction":null}}'}),
   ('1781925133717-3',
    {'default': '{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"before"},{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"int64","optional":true,"field":"txId"},{"type":"int64","optional":true,"field":"lsn"},{"type":"int64","optional":true,"field":"xmin"}],"optional":false,"name":"io.debezium.connector.postgresql.Source","field":"source"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"}],"optional":false,"name":"cdc.public.mapping_id.Envelope","version":1},"payload":{"before":null,"after":{"index":4,"id":4,"uuid":"a458cc4c-b2cb-4a81-a9c0-49eb79f03fa5"},"source":{"version":"2.4.2.Final","connector":"postgresql","name":"cdc","ts_ms":1781925133176,"snapshot":"false","db":"sourcedb","sequence":"[null,\\"29461656\\"]","schema":"public","table":"mapping_id","txId":767,"lsn":29461656,"xmin":null},"op":"c","ts_ms":1781925133370,"transaction":null}}'}),
   ('1781925133717-4',
    {'default': '{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"before"},{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"int64","optional":true,"field":"txId"},{"type":"int64","optional":true,"field":"lsn"},{"type":"int64","optional":true,"field":"xmin"}],"optional":false,"name":"io.debezium.connector.postgresql.Source","field":"source"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"}],"optional":false,"name":"cdc.public.mapping_id.Envelope","version":1},"payload":{"before":null,"after":{"index":5,"id":5,"uuid":"f56762ca-60b5-4486-8f21-2ead00932a3a"},"source":{"version":"2.4.2.Final","connector":"postgresql","name":"cdc","ts_ms":1781925133176,"snapshot":"false","db":"sourcedb","sequence":"[null,\\"29461832\\"]","schema":"public","table":"mapping_id","txId":767,"lsn":29461832,"xmin":null},"op":"c","ts_ms":1781925133370,"transaction":null}}'}),
   ('1781925133717-5',
    {'default': '{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"before"},{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"int64","optional":true,"field":"txId"},{"type":"int64","optional":true,"field":"lsn"},{"type":"int64","optional":true,"field":"xmin"}],"optional":false,"name":"io.debezium.connector.postgresql.Source","field":"source"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"}],"optional":false,"name":"cdc.public.mapping_id.Envelope","version":1},"payload":{"before":null,"after":{"index":6,"id":6,"uuid":"e1ce5f1c-f725-4fee-b528-bdbc1326aaa4"},"source":{"version":"2.4.2.Final","connector":"postgresql","name":"cdc","ts_ms":1781925133176,"snapshot":"false","db":"sourcedb","sequence":"[null,\\"29462008\\"]","schema":"public","table":"mapping_id","txId":767,"lsn":29462008,"xmin":null},"op":"c","ts_ms":1781925133370,"transaction":null}}'}),
   ('1781925133717-6',
    {'default': '{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"before"},{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"int64","optional":true,"field":"txId"},{"type":"int64","optional":true,"field":"lsn"},{"type":"int64","optional":true,"field":"xmin"}],"optional":false,"name":"io.debezium.connector.postgresql.Source","field":"source"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"}],"optional":false,"name":"cdc.public.mapping_id.Envelope","version":1},"payload":{"before":null,"after":{"index":7,"id":7,"uuid":"35395f82-ada9-49f7-b261-5e95c8725996"},"source":{"version":"2.4.2.Final","connector":"postgresql","name":"cdc","ts_ms":1781925133176,"snapshot":"false","db":"sourcedb","sequence":"[null,\\"29462184\\"]","schema":"public","table":"mapping_id","txId":767,"lsn":29462184,"xmin":null},"op":"c","ts_ms":1781925133371,"transaction":null}}'}),
   ('1781925133717-7',

## message
- [0] for list in list 
- [0][0] key name
- [0][1] data

In [37]:
data = messages[0][1]
data

[('1781925133716-0',
  {'default': '{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"before"},{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"int64","optional":true,"field":"txId"},{"type":"int64","optional":true,"field":"lsn"},{"type":"int64","optional":true,"field":"xmin"}],"optional":false,"name":"io.debezium.connector.postgresql.Source","field":"source"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"}],"optional":false,"name":"cdc.public.mapping_id.Envelope","version":1},"payload":{"before":null,"after":{"index":0,"id":0,"uuid":"5039f86c-379a-462a-a8c5-a7195f9ed43e"},"source":{"version":"2.4.2.Final","connector":"postgresql","name":"cdc","ts_ms":1781925133176,"snapshot":"false","db":"sourcedb","sequence":"[null,\\"29460856\\"]","schema":"public","table":"mapping_id","txId":767,"lsn":29460856,"xmin":null},"op":"c","ts_ms":1781925133366,"transaction":null}}'}),
 ('1781925133717-0',
  {'default': '{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"before"},{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"int64","optional":true,"field":"txId"},{"type":"int64","optional":true,"field":"lsn"},{"type":"int64","optional":true,"field":"xmin"}],"optional":false,"name":"io.debezium.connector.postgresql.Source","field":"source"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"}],"optional":false,"name":"cdc.public.mapping_id.Envelope","version":1},"payload":{"before":null,"after":{"index":1,"id":1,"uuid":"e58a4d31-3dde-4435-8eb9-375642eb238f"},"source":{"version":"2.4.2.Final","connector":"postgresql","name":"cdc","ts_ms":1781925133176,"snapshot":"false","db":"sourcedb","sequence":"[null,\\"29461128\\"]","schema":"public","table":"mapping_id","txId":767,"lsn":29461128,"xmin":null},"op":"c","ts_ms":1781925133369,"transaction":null}}'}),
 ('1781925133717-1',
  {'default': '{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"before"},{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"int64","optional":true,"field":"txId"},{"type":"int64","optional":true,"field":"lsn"},{"type":"int64","optional":true,"field":"xmin"}],"optional":false,"name":"io.debezium.connector.postgresql.Source","field":"source"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"}],"optional":false,"name":"cdc.public.mapping_id.Envelope","version":1},"payload":{"before":null,"after":{"index":2,"id":2,"uuid":"2fb18656-b37e-44ea-be63-daedb0248def"},"source":{"version":"2.4.2.Final","connector":"postgresql","name":"cdc","ts_ms":1781925133176,"snapshot":"false","db":"sourcedb","sequence":"[null,\\"29461304\\"]","schema":"public","table":"mapping_id","txId":767,"lsn":29461304,"xmin":null},"op":"c","ts_ms":1781925133369,"transaction":null}}'}),
 ('1781925133717-2',
  {'default': '{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"before"},{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"int64","optional":true,"field":"txId"},{"type":"int64","optional":true,"field":"lsn"},{"type":"int64","optional":true,"field":"xmin"}],"optional":false,"name":"io.debezium.connector.postgresql.Source","field":"source"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"}],"optional":false,"name":"cdc.public.mapping_id.Envelope","version":1},"payload":{"before":null,"after":{"index":3,"id":3,"uuid":"d5a9d0da-ce82-447a-b764-b3ad028fc300"},"source":{"version":"2.4.2.Final","connector":"postgresql","name":"cdc","ts_ms":1781925133176,"snapshot":"false","db":"sourcedb","sequence":"[null,\\"29461480\\"]","schema":"public","table":"mapping_id","txId":767,"lsn":29461480,"xmin":null},"op":"c","ts_ms":1781925133370,"transaction":null}}'}),
 ('1781925133717-3',
  {'default': '{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"before"},{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"int64","optional":true,"field":"txId"},{"type":"int64","optional":true,"field":"lsn"},{"type":"int64","optional":true,"field":"xmin"}],"optional":false,"name":"io.debezium.connector.postgresql.Source","field":"source"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"}],"optional":false,"name":"cdc.public.mapping_id.Envelope","version":1},"payload":{"before":null,"after":{"index":4,"id":4,"uuid":"a458cc4c-b2cb-4a81-a9c0-49eb79f03fa5"},"source":{"version":"2.4.2.Final","connector":"postgresql","name":"cdc","ts_ms":1781925133176,"snapshot":"false","db":"sourcedb","sequence":"[null,\\"29461656\\"]","schema":"public","table":"mapping_id","txId":767,"lsn":29461656,"xmin":null},"op":"c","ts_ms":1781925133370,"transaction":null}}'}),
 ('1781925133717-4',
  {'default': '{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"before"},{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"int64","optional":true,"field":"txId"},{"type":"int64","optional":true,"field":"lsn"},{"type":"int64","optional":true,"field":"xmin"}],"optional":false,"name":"io.debezium.connector.postgresql.Source","field":"source"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"}],"optional":false,"name":"cdc.public.mapping_id.Envelope","version":1},"payload":{"before":null,"after":{"index":5,"id":5,"uuid":"f56762ca-60b5-4486-8f21-2ead00932a3a"},"source":{"version":"2.4.2.Final","connector":"postgresql","name":"cdc","ts_ms":1781925133176,"snapshot":"false","db":"sourcedb","sequence":"[null,\\"29461832\\"]","schema":"public","table":"mapping_id","txId":767,"lsn":29461832,"xmin":null},"op":"c","ts_ms":1781925133370,"transaction":null}}'}),
 ('1781925133717-5',
  {'default': '{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"before"},{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"int64","optional":true,"field":"txId"},{"type":"int64","optional":true,"field":"lsn"},{"type":"int64","optional":true,"field":"xmin"}],"optional":false,"name":"io.debezium.connector.postgresql.Source","field":"source"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"}],"optional":false,"name":"cdc.public.mapping_id.Envelope","version":1},"payload":{"before":null,"after":{"index":6,"id":6,"uuid":"e1ce5f1c-f725-4fee-b528-bdbc1326aaa4"},"source":{"version":"2.4.2.Final","connector":"postgresql","name":"cdc","ts_ms":1781925133176,"snapshot":"false","db":"sourcedb","sequence":"[null,\\"29462008\\"]","schema":"public","table":"mapping_id","txId":767,"lsn":29462008,"xmin":null},"op":"c","ts_ms":1781925133370,"transaction":null}}'}),
 ('1781925133717-6',
  {'default': '{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"before"},{"type":"struct","fields":[{"type":"int64","optional":true,"field":"index"},{"type":"int64","optional":true,"field":"id"},{"type":"string","optional":true,"field":"uuid"}],"optional":true,"name":"cdc.public.mapping_id.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"int64","optional":true,"field":"txId"},{"type":"int64","optional":true,"field":"lsn"},{"type":"int64","optional":true,"field":"xmin"}],"optional":false,"name":"io.debezium.connector.postgresql.Source","field":"source"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"}],"optional":false,"name":"cdc.public.mapping_id.Envelope","version":1},"payload":{"before":null,"after":{"index":7,"id":7,"uuid":"35395f82-ada9-49f7-b261-5e95c8725996"},"source":{"version":"2.4.2.Final","connector":"postgresql","name":"cdc","ts_ms":1781925133176,"snapshot":"false","db":"sourcedb","sequence":"[null,\\"29462184\\"]","schema":"public","table":"mapping_id","txId":767,"lsn":29462184,"xmin":null},"op":"c","ts_ms":1781925133371,"transaction":null}}'}),
 ('1781925133717-7',

# data => list 
- data[0] 1st element
- data[0][0] -> id
- data[0][1] -> data(dict)

In [55]:
elm = json.loads(data[0][1]['default'])
elm

{'schema': {'type': 'struct',
  'fields': [{'type': 'struct',
    'fields': [{'type': 'int64', 'optional': True, 'field': 'index'},
     {'type': 'int64', 'optional': True, 'field': 'id'},
     {'type': 'string', 'optional': True, 'field': 'uuid'}],
    'optional': True,
    'name': 'cdc.public.mapping_id.Value',
    'field': 'before'},
   {'type': 'struct',
    'fields': [{'type': 'int64', 'optional': True, 'field': 'index'},
     {'type': 'int64', 'optional': True, 'field': 'id'},
     {'type': 'string', 'optional': True, 'field': 'uuid'}],
    'optional': True,
    'name': 'cdc.public.mapping_id.Value',
    'field': 'after'},
   {'type': 'struct',
    'fields': [{'type': 'string', 'optional': False, 'field': 'version'},
     {'type': 'string', 'optional': False, 'field': 'connector'},
     {'type': 'string', 'optional': False, 'field': 'name'},
     {'type': 'int64', 'optional': False, 'field': 'ts_ms'},
     {'type': 'string',
      'optional': True,
      'name': 'io.debezium.data.Enum',
      'version': 1,
      'parameters': {'allowed': 'true,last,false,incremental'},
      'default': 'false',
      'field': 'snapshot'},
     {'type': 'string', 'optional': False, 'field': 'db'},
     {'type': 'string', 'optional': True, 'field': 'sequence'},
     {'type': 'string', 'optional': False, 'field': 'schema'},
     {'type': 'string', 'optional': False, 'field': 'table'},
     {'type': 'int64', 'optional': True, 'field': 'txId'},
     {'type': 'int64', 'optional': True, 'field': 'lsn'},
     {'type': 'int64', 'optional': True, 'field': 'xmin'}],
    'optional': False,
    'name': 'io.debezium.connector.postgresql.Source',
    'field': 'source'},
   {'type': 'string', 'optional': False, 'field': 'op'},
   {'type': 'int64', 'optional': True, 'field': 'ts_ms'},
   {'type': 'struct',
    'fields': [{'type': 'string', 'optional': False, 'field': 'id'},
     {'type': 'int64', 'optional': False, 'field': 'total_order'},
     {'type': 'int64', 'optional': False, 'field': 'data_collection_order'}],
    'optional': True,
    'name': 'event.block',
    'version': 1,
    'field': 'transaction'}],
  'optional': False,
  'name': 'cdc.public.mapping_id.Envelope',
  'version': 1},
 'payload': {'before': None,
  'after': {'index': 0,
   'id': 0,
   'uuid': '5039f86c-379a-462a-a8c5-a7195f9ed43e'},
  'source': {'version': '2.4.2.Final',
   'connector': 'postgresql',
   'name': 'cdc',
   'ts_ms': 1781925133176,
   'snapshot': 'false',
   'db': 'sourcedb',
   'sequence': '[null,"29460856"]',
   'schema': 'public',
   'table': 'mapping_id',
   'txId': 767,
   'lsn': 29460856,
   'xmin': None},
  'op': 'c',
  'ts_ms': 1781925133366,
  'transaction': None}}

In [59]:
elm['payload']['after']

{'index': 0, 'id': 0, 'uuid': '5039f86c-379a-462a-a8c5-a7195f9ed43e'}

In [84]:
import pandas as pd
import s3fs

In [85]:
# pip install s3fs

In [70]:
df = pd.DataFrame([
    json.loads(elm[1]['default'])['payload']['after']
    for elm in data
])
df

   index  id                                  uuid
0      0   0  5039f86c-379a-462a-a8c5-a7195f9ed43e
1      1   1  e58a4d31-3dde-4435-8eb9-375642eb238f
2      2   2  2fb18656-b37e-44ea-be63-daedb0248def
3      3   3  d5a9d0da-ce82-447a-b764-b3ad028fc300
4      4   4  a458cc4c-b2cb-4a81-a9c0-49eb79f03fa5
5      5   5  f56762ca-60b5-4486-8f21-2ead00932a3a
6      6   6  e1ce5f1c-f725-4fee-b528-bdbc1326aaa4
7      7   7  35395f82-ada9-49f7-b261-5e95c8725996
8      8   8  ed220d84-cbb8-4354-ae4b-04d897772ae0
9      9   9  607f8935-0553-4dc9-910a-3e42db5377b6

In [77]:
datas = []
for event_id, event_data in messages[0][1]:
    data = json.loads(event_data['default'])
    datas.append(data)
    redis_client.xdel(STREAM_KEY, event_id)

In [80]:
df = pd.DataFrame([
    elm.get('payload').get('after')
for elm in datas])
df

   index  id                                  uuid
0      0   0  5039f86c-379a-462a-a8c5-a7195f9ed43e
1      1   1  e58a4d31-3dde-4435-8eb9-375642eb238f
2      2   2  2fb18656-b37e-44ea-be63-daedb0248def
3      3   3  d5a9d0da-ce82-447a-b764-b3ad028fc300
4      4   4  a458cc4c-b2cb-4a81-a9c0-49eb79f03fa5
5      5   5  f56762ca-60b5-4486-8f21-2ead00932a3a
6      6   6  e1ce5f1c-f725-4fee-b528-bdbc1326aaa4
7      7   7  35395f82-ada9-49f7-b261-5e95c8725996
8      8   8  ed220d84-cbb8-4354-ae4b-04d897772ae0
9      9   9  607f8935-0553-4dc9-910a-3e42db5377b6

In [86]:
STREAM_KEY_ORACLE = 'cdc-oracle.C__APPUSER.CUSTOMERS'

In [108]:
messages = redis_client.xread({STREAM_KEY_ORACLE: last_id}, count=10, block=5000)
messages

[['cdc-oracle.C__APPUSER.CUSTOMERS',
  [('1781960944951-0',
    {'{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int32","optional":false,"field":"scale"},{"type":"bytes","optional":false,"field":"value"}],"optional":false,"name":"io.debezium.data.VariableScaleDecimal","version":1,"doc":"Variable scaled decimal","field":"ID"}],"optional":false,"name":"cdc-oracle.C__APPUSER.CUSTOMERS.Key"},"payload":{"ID":{"scale":0,"value":"AQ=="}}}': '{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int32","optional":false,"field":"scale"},{"type":"bytes","optional":false,"field":"value"}],"optional":false,"name":"io.debezium.data.VariableScaleDecimal","version":1,"doc":"Variable scaled decimal","field":"ID"},{"type":"string","optional":true,"field":"NAME"},{"type":"string","optional":true,"field":"EMAIL"}],"optional":true,"name":"cdc-oracle.C__APPUSER.CUSTOMERS.Value","field":"before"},{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int32","optional":false,"field":"scale"},{"type":"bytes","optional":false,"field":"value"}],"optional":false,"name":"io.debezium.data.VariableScaleDecimal","version":1,"doc":"Variable scaled decimal","field":"ID"},{"type":"string","optional":true,"field":"NAME"},{"type":"string","optional":true,"field":"EMAIL"}],"optional":true,"name":"cdc-oracle.C__APPUSER.CUSTOMERS.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"int64","optional":true,"field":"ts_us"},{"type":"int64","optional":true,"field":"ts_ns"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"string","optional":true,"field":"txId"},{"type":"string","optional":true,"field":"scn"},{"type":"string","optional":true,"field":"commit_scn"},{"type":"string","optional":true,"field":"lcr_position"},{"type":"string","optional":true,"field":"rs_id"},{"type":"int64","optional":true,"field":"ssn"},{"type":"int32","optional":true,"field":"redo_thread"},{"type":"string","optional":true,"field":"user_name"},{"type":"string","optional":true,"field":"redo_sql"},{"type":"string","optional":true,"field":"row_id"}],"optional":false,"name":"io.debezium.connector.oracle.Source","field":"source"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"int64","optional":true,"field":"ts_us"},{"type":"int64","optional":true,"field":"ts_ns"}],"optional":false,"name":"cdc-oracle.C__APPUSER.CUSTOMERS.Envelope","version":2},"payload":{"before":null,"after":{"ID":{"scale":0,"value":"AQ=="},"NAME":"Test User","EMAIL":"test@example.com"},"source":{"version":"2.7.4.Final","connector":"oracle","name":"cdc-oracle","ts_ms":1781960941000,"snapshot":"false","db":"FREE","sequence":null,"ts_us":1781960941000000,"ts_ns":1781960941000000000,"schema":"C##APPUSER","table":"CUSTOMERS","txId":"0a00030042020000","scn":"2177172","commit_scn":"2177174","lcr_position":null,"rs_id":"0x000009.0004ef92.00dc","ssn":0,"redo_thread":1,"user_name":"C##APPUSER","redo_sql":null,"row_id":"AAARvQAAAAAAAMXAAA"},"transaction":null,"op":"c","ts_ms":1781960944506,"ts_us":1781960944506447,"ts_ns":1781960944506447000}}'}),
   ('1781961303347-0',
    {'{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int32","optional":false,"field":"scale"},{"type":"bytes","optional":false,"field":"value"}],"optional":false,"name":"io.debezium.data.VariableScaleDecimal","version":1,"doc":"Variable scaled decimal","field":"ID"}],"optional":false,"name":"cdc-oracle.C__APPUSER.CUSTOMERS.Key"},"payload":{"ID":{"scale":0,"value":"FQ=="}}}': '{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int32","optional":false,"field":"scale"},{"type":"bytes","optional":false,"field":"value"}],"optional":false,"name":"io.debezium.data.VariableScaleDecimal","version":1,"doc":"Variable scaled decimal","field":"ID"},{"type":"string","optional":true,"field":"NAME"},{"type":"string","optional":true,"field":"EMAIL"}],"optional":true,"name":"cdc-oracle.C__APPUSER.CUSTOMERS.Value","field":"before"},{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int32","optional":false,"field":"scale"},{"type":"bytes","optional":false,"field":"value"}],"optional":false,"name":"io.debezium.data.VariableScaleDecimal","version":1,"doc":"Variable scaled decimal","field":"ID"},{"type":"string","optional":true,"field":"NAME"},{"type":"string","optional":true,"field":"EMAIL"}],"optional":true,"name":"cdc-oracle.C__APPUSER.CUSTOMERS.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"int64","optional":true,"field":"ts_us"},{"type":"int64","optional":true,"field":"ts_ns"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"string","optional":true,"field":"txId"},{"type":"string","optional":true,"field":"scn"},{"type":"string","optional":true,"field":"commit_scn"},{"type":"string","optional":true,"field":"lcr_position"},{"type":"string","optional":true,"field":"rs_id"},{"type":"int64","optional":true,"field":"ssn"},{"type":"int32","optional":true,"field":"redo_thread"},{"type":"string","optional":true,"field":"user_name"},{"type":"string","optional":true,"field":"redo_sql"},{"type":"string","optional":true,"field":"row_id"}],"optional":false,"name":"io.debezium.connector.oracle.Source","field":"source"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"int64","optional":true,"field":"ts_us"},{"type":"int64","optional":true,"field":"ts_ns"}],"optional":false,"name":"cdc-oracle.C__APPUSER.CUSTOMERS.Envelope","version":2},"payload":{"before":null,"after":{"ID":{"scale":0,"value":"FQ=="},"NAME":"Robin Herrera","EMAIL":"kenneth37@example.org"},"source":{"version":"2.7.4.Final","connector":"oracle","name":"cdc-oracle","ts_ms":1781961300000,"snapshot":"false","db":"FREE","sequence":null,"ts_us":1781961300000000,"ts_ns":1781961300000000000,"schema":"C##APPUSER","table":"CUSTOMERS","txId":"01001f0047020000","scn":"2233178","commit_scn":"2233180","lcr_position":null,"rs_id":"0x00000e.00052b80.0010","ssn":0,"redo_thread":1,"user_name":"SYSTEM","redo_sql":null,"row_id":"AAARvQAAAAAAAMUAAA"},"transaction":null,"op":"c","ts_ms":1781961303104,"ts_us":1781961303104159,"ts_ns":1781961303104159000}}'}),
   ('1781961303348-0',
    {'{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int32","optional":false,"field":"scale"},{"type":"bytes","optional":false,"field":"value"}],"optional":false,"name":"io.debezium.data.VariableScaleDecimal","version":1,"doc":"Variable scaled decimal","field":"ID"}],"optional":false,"name":"cdc-oracle.C__APPUSER.CUSTOMERS.Key"},"payload":{"ID":{"scale":0,"value":"Fg=="}}}': '{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int32","optional":false,"field":"scale"},{"type":"bytes","optional":false,"field":"value"}],"optional":false,"name":"io.debezium.data.VariableScaleDecimal","version":1,"doc":"Variable scaled decimal","field":"ID"},{"type":"string","optional":true,"field":"NAME"},{"type":"string","optional":true,"field":"EMAIL"}],"optional":true,"name":"cdc-oracle.C__APPUSER.CUSTOMERS.Value","field":"before"},{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int32","optional":false,"field":"scale"},{"type":"bytes","optional":false,"field":"value"}],"optional":false,"name":"io.debezium.data.VariableScaleDecimal","version":1,"doc":"Variable scaled decimal","field":"ID"},{"type":"string","optional":true,"field":"NAME"},{"type":"string","optional":true,"field":"EMAIL"}],"optional":true,"name":"cdc-oracle.C__APPUSER.CUSTOMERS.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"int64","optional":true,"field":"ts_us"},{"type":"int64","optional":true,"field":"ts_ns"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"string","optional":true,"field":"txId"},{"type":"string","optional":true,"field":"scn"},{"type":"string","optional":true,"field":"commit_scn"},{"type":"string","optional":true,"field":"lcr_position"},{"type":"string","optional":true,"field":"rs_id"},{"type":"int64","optional":true,"field":"ssn"},{"type":"int32","optional":true,"field":"redo_thread"},{"type":"string","optional":true,"field":"user_name"},{"type":"string","optional":true,"field":"redo_sql"},{"type":"string","optional":true,"field":"row_id"}],"optional":false,"name":"io.debezium.connector.oracle.Source","field":"source"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"int64","optional":true,"field":"ts_us"},{"type":"int64","optional":true,"field":"ts_ns"}],"optional":false,"name":"cdc-oracle.C__APPUSER.CUSTOMERS.Envelope","version":2},"payload":{"before":null,"after":{"ID":{"scale":0,"value":"Fg=="},"NAME":"Kimberly Cameron","EMAIL":"qmccormick@example.org"},"source":{"version":"2.7.4.Final","connector":"oracle","name":"cdc-oracle","ts_ms":1781961300000,"snapshot":"false","db":"FREE","sequence":null,"ts_us":1781961300000000,"ts_ns":1781961300000000000,"schema":"C##APPUSER","table":"CUSTOMERS","txId":"01001f0047020000","scn":"2233178","commit_scn":"2233180","lcr_position":null,"rs_id":"0x00000e.00052b80.0010","ssn":0,"redo_thread":1,"user_name":"SYSTEM","redo_sql":null,"row_id":"AAARvQAAAAAAAMUAAB"},"transaction":null,"op":"c","ts_ms":1781961303104,"ts_us":1781961303104832,"ts_ns":1781961303104832000}}'}),
   ('1781961303348-1',
    {'{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int32","optional":false,"field":"scale"},{"type":"bytes","optional":false,"field":"value"}],"optional":false,"name":"io.debezium.data.VariableScaleDecimal","version":1,"doc":"Variable scaled decimal","field":"ID"}],"optional":false,"name":"cdc-oracle.C__APPUSER.CUSTOMERS.Key"},"payload":{"ID":{"scale":0,"value":"Fw=="}}}': '{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int32","optional":false,"field":"scale"},{"type":"bytes","optional":false,"field":"value"}],"optional":false,"name":"io.debezium.data.VariableScaleDecimal","version":1,"doc":"Variable scaled decimal","field":"ID"},{"type":"string","optional":true,"field":"NAME"},{"type":"string","optional":true,"field":"EMAIL"}],"optional":true,"name":"cdc-oracle.C__APPUSER.CUSTOMERS.Value","field":"before"},{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int32","optional":false,"field":"scale"},{"type":"bytes","optional":false,"field":"value"}],"optional":false,"name":"io.debezium.data.VariableScaleDecimal","version":1,"doc":"Variable scaled decimal","field":"ID"},{"type":"string","optional":true,"field":"NAME"},{"type":"string","optional":true,"field":"EMAIL"}],"optional":true,"name":"cdc-oracle.C__APPUSER.CUSTOMERS.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"int64","optional":true,"field":"ts_us"},{"type":"int64","optional":true,"field":"ts_ns"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"string","optional":true,"field":"txId"},{"type":"string","optional":true,"field":"scn"},{"type":"string","optional":true,"field":"commit_scn"},{"type":"string","optional":true,"field":"lcr_position"},{"type":"string","optional":true,"field":"rs_id"},{"type":"int64","optional":true,"field":"ssn"},{"type":"int32","optional":true,"field":"redo_thread"},{"type":"string","optional":true,"field":"user_name"},{"type":"string","optional":true,"field":"redo_sql"},{"type":"string","optional":true,"field":"row_id"}],"optional":false,"name":"io.debezium.connector.oracle.Source","field":"source"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"int64","optional":true,"field":"ts_us"},{"type":"int64","optional":true,"field":"ts_ns"}],"optional":false,"name":"cdc-oracle.C__APPUSER.CUSTOMERS.Envelope","version":2},"payload":{"before":null,"after":{"ID":{"scale":0,"value":"Fw=="},"NAME":"Janice Lam","EMAIL":"colleen23@example.org"},"source":{"version":"2.7.4.Final","connector":"oracle","name":"cdc-oracle","ts_ms":1781961300000,"snapshot":"false","db":"FREE","sequence":null,"ts_us":1781961300000000,"ts_ns":1781961300000000000,"schema":"C##APPUSER","table":"CUSTOMERS","txId":"01001f0047020000","scn":"2233178","commit_scn":"2233180","lcr_position":null,"rs_id":"0x00000e.00052b80.0010","ssn":0,"redo_thread":1,"user_name":"SYSTEM","redo_sql":null,"row_id":"AAARvQAAAAAAAMUAAC"},"transaction":null,"op":"c","ts_ms":1781961303104,"ts_us":1781961303104966,"ts_ns":1781961303104966000}}'}),
   ('1781961303348-2',
    {'{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int32","optional":false,"field":"scale"},{"type":"bytes","optional":false,"field":"value"}],"optional":false,"name":"io.debezium.data.VariableScaleDecimal","version":1,"doc":"Variable scaled decimal","field":"ID"}],"optional":false,"name":"cdc-oracle.C__APPUSER.CUSTOMERS.Key"},"payload":{"ID":{"scale":0,"value":"GA=="}}}': '{"schema":{"type":"struct","fields":[{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int32","optional":false,"field":"scale"},{"type":"bytes","optional":false,"field":"value"}],"optional":false,"name":"io.debezium.data.VariableScaleDecimal","version":1,"doc":"Variable scaled decimal","field":"ID"},{"type":"string","optional":true,"field":"NAME"},{"type":"string","optional":true,"field":"EMAIL"}],"optional":true,"name":"cdc-oracle.C__APPUSER.CUSTOMERS.Value","field":"before"},{"type":"struct","fields":[{"type":"struct","fields":[{"type":"int32","optional":false,"field":"scale"},{"type":"bytes","optional":false,"field":"value"}],"optional":false,"name":"io.debezium.data.VariableScaleDecimal","version":1,"doc":"Variable scaled decimal","field":"ID"},{"type":"string","optional":true,"field":"NAME"},{"type":"string","optional":true,"field":"EMAIL"}],"optional":true,"name":"cdc-oracle.C__APPUSER.CUSTOMERS.Value","field":"after"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"version"},{"type":"string","optional":false,"field":"connector"},{"type":"string","optional":false,"field":"name"},{"type":"int64","optional":false,"field":"ts_ms"},{"type":"string","optional":true,"name":"io.debezium.data.Enum","version":1,"parameters":{"allowed":"true,last,false,incremental"},"default":"false","field":"snapshot"},{"type":"string","optional":false,"field":"db"},{"type":"string","optional":true,"field":"sequence"},{"type":"int64","optional":true,"field":"ts_us"},{"type":"int64","optional":true,"field":"ts_ns"},{"type":"string","optional":false,"field":"schema"},{"type":"string","optional":false,"field":"table"},{"type":"string","optional":true,"field":"txId"},{"type":"string","optional":true,"field":"scn"},{"type":"string","optional":true,"field":"commit_scn"},{"type":"string","optional":true,"field":"lcr_position"},{"type":"string","optional":true,"field":"rs_id"},{"type":"int64","optional":true,"field":"ssn"},{"type":"int32","optional":true,"field":"redo_thread"},{"type":"string","optional":true,"field":"user_name"},{"type":"string","optional":true,"field":"redo_sql"},{"type":"string","optional":true,"field":"row_id"}],"optional":false,"name":"io.debezium.connector.oracle.Source","field":"source"},{"type":"struct","fields":[{"type":"string","optional":false,"field":"id"},{"type":"int64","optional":false,"field":"total_order"},{"type":"int64","optional":false,"field":"data_collection_order"}],"optional":true,"name":"event.block","version":1,"field":"transaction"},{"type":"string","optional":false,"field":"op"},{"type":"int64","optional":true,"field":"ts_ms"},{"type":"int64","optional":true,"field":"ts_us"},{"type":"int64","optional":true,"field":"ts_ns"}],"optional":false,"name":"cdc-oracle.C__APPUSER.CUSTOMERS.Envelope","version":2},"payload":{"before":null,"after":{"ID":{"scale":0,"value":"GA=="},"NAME":"Shelia Martinez","EMAIL":"jameshenderson@example.org"},"source":{"version":"2.7.4.Final","connector":"oracle","name":"cdc-oracle","ts_ms":1781961300000,"snapshot":"false","db":"FREE","sequence":null,"ts_us":1781961300000000,"ts_ns":1781961300000000000,"schema":"C##APPUSER","table":"CUSTOMERS","txId":"01001f0047020000","scn":"2233178","commit_scn":"2233180","lcr_position":null,"rs_id":"0x00000e.00052b80.0010","ssn":0,"redo_thread":1,"user_name":"SYSTEM","redo_sql":null,"row_id":"AAARvQAAAAAAAMUAAD"},"transaction":null,"op":"c","ts_ms":1781961303105,"ts_us":1781961303105169,"ts_ns":1781961303105169000}}'}),
   ('1781961303348-3',

In [131]:
datas = []
for event_id, event_data in messages[0][1]:
    data = json.loads(event_data[list(event_data.keys())[0]])
    datas.append(data)
    redis_client.xdel(STREAM_KEY_ORACLE, event_id)

In [132]:
df = pd.DataFrame([
    elm.get('payload').get('after')
for elm in datas])
df

                              ID              NAME                       EMAIL
0  {'scale': 0, 'value': 'AQ=='}         Test User            test@example.com
1  {'scale': 0, 'value': 'FQ=='}     Robin Herrera       kenneth37@example.org
2  {'scale': 0, 'value': 'Fg=='}  Kimberly Cameron      qmccormick@example.org
3  {'scale': 0, 'value': 'Fw=='}        Janice Lam       colleen23@example.org
4  {'scale': 0, 'value': 'GA=='}   Shelia Martinez  jameshenderson@example.org
5  {'scale': 0, 'value': 'GQ=='}   Cassidy Jenkins          cmarks@example.net
6  {'scale': 0, 'value': 'Gg=='}      Robin Obrien   sarahhamilton@example.net
7  {'scale': 0, 'value': 'Gw=='}     Richard Moore       wmartinez@example.org
8  {'scale': 0, 'value': 'HA=='}      Aaron Jordan       hudsonzoe@example.net
9  {'scale': 0, 'value': 'HQ=='}       Shawn Mcgee        psanchez@example.com